from io import BytesIO
from decimal import Decimal

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import mm


def money(x: Decimal) -> str:
    return f"GHS {x:,.2f}"


def invoice_pdf_bytes(invoice) -> bytes:
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    width, height = A4

    y = height - 20 * mm
    c.setFont("Helvetica-Bold", 14)
    c.drawString(20 * mm, y, "SAMDA-IT Consult")
    y -= 7 * mm

    c.setFont("Helvetica", 10)
    c.drawString(20 * mm, y, f"Invoice No: {invoice.invoice_no}"); y -= 5 * mm
    c.drawString(20 * mm, y, f"Invoice Type: {invoice.get_invoice_type_display()}"); y -= 5 * mm
    c.drawString(20 * mm, y, f"Issue Date: {invoice.issue_date}"); y -= 5 * mm
    c.drawString(20 * mm, y, f"Customer: {invoice.customer.name}"); y -= 10 * mm

    c.setFont("Helvetica-Bold", 10)
    c.drawString(20 * mm, y, "Description")
    c.drawString(120 * mm, y, "Qty")
    c.drawString(140 * mm, y, "Rate")
    c.drawString(170 * mm, y, "Amount")
    y -= 4 * mm
    c.line(20 * mm, y, 190 * mm, y)
    y -= 6 * mm

    c.setFont("Helvetica", 10)
    for ln in invoice.lines.all():
        if y < 30 * mm:
            c.showPage()
            y = height - 20 * mm
        c.drawString(20 * mm, y, ln.description[:55])
        c.drawRightString(135 * mm, y, f"{ln.qty}")
        c.drawRightString(160 * mm, y, money(ln.unit_price))
        c.drawRightString(190 * mm, y, money(ln.line_total()))
        y -= 6 * mm

    y -= 6 * mm
    c.line(120 * mm, y, 190 * mm, y)
    y -= 8 * mm

    c.setFont("Helvetica-Bold", 10)
    c.drawRightString(160 * mm, y, "Subtotal:")
    c.drawRightString(190 * mm, y, money(invoice.subtotal)); y -= 6 * mm

    if invoice.invoice_type == "VAT":
        c.setFont("Helvetica", 10)
        c.drawRightString(160 * mm, y, "VAT (15%):")
        c.drawRightString(190 * mm, y, money(invoice.vat)); y -= 6 * mm
        c.drawRightString(160 * mm, y, "NHIL (2.5%):")
        c.drawRightString(190 * mm, y, money(invoice.nhil)); y -= 6 * mm
        c.drawRightString(160 * mm, y, "GETFund (2.5%):")
        c.drawRightString(190 * mm, y, money(invoice.getfund)); y -= 6 * mm

    c.setFont("Helvetica-Bold", 11)
    c.drawRightString(160 * mm, y, "Total:")
    c.drawRightString(190 * mm, y, money(invoice.total)); y -= 8 * mm

    c.setFont("Helvetica", 10)
    c.drawString(20 * mm, y, f"Amount Paid: {money(invoice.amount_paid())}"); y -= 5 * mm
    c.drawString(20 * mm, y, f"Balance Due: {money(invoice.balance_due())}")

    c.setFont("Helvetica", 9)
    c.drawString(20 * mm, 15 * mm, "Generated by SAMDA Accounts App (MVP).")
    c.save()
    return buf.getvalue()


def receipt_pdf_bytes(receipt) -> bytes:
    payment = receipt.payment
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    width, height = A4

    y = height - 20 * mm
    c.setFont("Helvetica-Bold", 16)
    c.drawString(20 * mm, y, "OFFICIAL RECEIPT")
    y -= 8 * mm

    c.setFont("Helvetica-Bold", 14)
    c.drawString(20 * mm, y, "SAMDA-IT Consult")
    y -= 7 * mm

    c.setFont("Helvetica", 10)
    c.drawString(20 * mm, y, f"Receipt No: {receipt.receipt_no}"); y -= 5 * mm
    c.drawString(20 * mm, y, f"Issued Date: {receipt.issued_date}"); y -= 5 * mm
    c.drawString(20 * mm, y, f"Received Date: {payment.received_date}"); y -= 5 * mm
    c.drawString(20 * mm, y, f"Payer: {payment.payer_name}"); y -= 5 * mm
    c.drawString(20 * mm, y, f"Method: {payment.get_method_display()}"); y -= 5 * mm
    if payment.reference:
        c.drawString(20 * mm, y, f"Reference: {payment.reference}"); y -= 5 * mm

    y -= 5 * mm
    c.line(20 * mm, y, 190 * mm, y); y -= 8 * mm

    c.setFont("Helvetica-Bold", 10)
    c.drawString(20 * mm, y, "Applied To")
    c.drawRightString(190 * mm, y, "Amount")
    y -= 4 * mm
    c.line(20 * mm, y, 190 * mm, y)
    y -= 7 * mm

    c.setFont("Helvetica", 10)
    allocations = list(payment.allocations.select_related("invoice").all())
    if allocations:
        for alloc in allocations:
            inv = alloc.invoice
            c.drawString(20 * mm, y, f"Invoice {inv.invoice_no} - {inv.customer.name}"[:70])
            c.drawRightString(190 * mm, y, money(alloc.amount))
            y -= 6 * mm
    else:
        c.drawString(20 * mm, y, "Unallocated payment")
        c.drawRightString(190 * mm, y, money(payment.amount))
        y -= 6 * mm

    y -= 6 * mm
    c.line(120 * mm, y, 190 * mm, y); y -= 8 * mm

    c.setFont("Helvetica-Bold", 12)
    c.drawRightString(160 * mm, y, "Total Received:")
    c.drawRightString(190 * mm, y, money(payment.amount))

    c.setFont("Helvetica", 9)
    c.drawString(20 * mm, 15 * mm, "Thank you for your business.")
    c.save()
    return buf.getvalue()
